-- PostgreSQL schema for entity com.hellin.despliegue_api_rest.entity.Pet
-- Compatible con Neon y JPA GenerationType.IDENTITY

CREATE TABLE IF NOT EXISTS pet (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  born DATE NOT NULL,
  chip VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NULL
);

-- Datos iniciales (opcional)
INSERT INTO pet (name, born, chip, category) VALUES
('Mugu', '2017-09-12', '2r2r2r2r33y3y3', 'pinscher'),
('Ibra', '2005-12-09', '1r1r1r1r1r11r1', 'alfa'),
('Alonso', '2025-09-16', '2324GFee111111', 'champion');